services:
  # Base de données
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    hostname: db
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d shop_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Ngrok
  #ngrok:
    #image: ngrok/ngrok:debian
    #container_name: ngrok
    #hostname: ngrok
    #network_mode: host
    #restart: ${DOCKER_RESTART_POLICY}
    #environment:
      #- NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    #command:
      #- 'http'
      #- 'localhost:80'
      #- '--url=${NGROK_DOMAIN}'
    #depends_on:
      #- nginx
#
  # Reverse proxy
  #nginx:
    #image: nginx:alpine
    #container_name: nginx
    #hostname: nginx
    #restart: ${DOCKER_RESTART_POLICY}
    #ports:
      #- "${NGINX_PORT}:80"
    #volumes:
      #- ./docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    #depends_on:
      #- api
      #- bo
      #- shop

  # API
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
        USERNAME: ${USERNAME}
    container_name: api
    hostname: api
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - ./src/api:/var/www
      - ./docker/api/entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: ["entrypoint.sh"]
    user: ${USER_ID}:${GROUP_ID}
    depends_on:
      db:
        condition: service_healthy
#
  # Backoffice pour les équipes internes (commerciaux, communication, logistique, ...)
  bo:
    build:
      context: .
      dockerfile: docker/bo/Dockerfile.dev
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
        USERNAME: ${USERNAME}
    container_name: bo
    hostname: bo
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - REACT_APP_API_URL=${API_URL}
    volumes:
      - ./src/bo:/app
      - ./docker/bo/entrypoint.sh:/usr/local/bin/entrypoint.sh
    stdin_open: true
    entrypoint: ["entrypoint.sh"]
    user: ${USER_ID}:${GROUP_ID}
    depends_on:
      - api

  # Shop pour les clients
  shop:
    build:
      context: .
      dockerfile: docker/shop/Dockerfile.dev
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
        USERNAME: ${USERNAME}
    container_name: shop
    hostname: shop
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - REACT_APP_API_URL=${API_URL}
    volumes:
      - ./src/shop:/app
      - ./docker/shop/entrypoint.sh:/usr/local/bin/entrypoint.sh
    stdin_open: true
    entrypoint: ["entrypoint.sh"]
    user: ${USER_ID}:${GROUP_ID}
    depends_on:
      - api

networks:
  default:
    name: shop_network

volumes:
  db_data:
